image: magnetcoop/bob:2e3b8bc

pipelines:
  default:
    - step:
        script:
          - /usr/local/bin/all-checks.sh
          - ./ci/build-and-run-docker-image.sh
          - ./ci/lint-and-test.sh
        services:
          - docker
  tags:
    '*.*.*':
      - step:
          script:
            - export MVN_PRIVATE_REPO_USERNAME=$AWS_ACCESS_KEY_ID
            - export MVN_PRIVATE_REPO_PASSWORD=$AWS_SECRET_ACCESS_KEY
            - /usr/local/bin/all-checks.sh
            - ./ci/build-and-run-docker-image.sh
            - ./ci/lint-and-test.sh
            - ./ci/publish-jar.sh
          services:
            - docker
definitions:
  services:
    docker:
      memory: 3072
