image: magnetcoop/bob:2e3b8bc

pipelines:
  default:
    - step:
        script:
          - /usr/local/bin/all-checks.sh
          - ./ci/lint-and-test.sh
        services:
          - docker
  tags:
    '*.*.*':
      - step:
          script:
            - ./usr/local/bin/all-checks.sh
            - ./ci/lint-and-test.sh
            - ./ci/publish-jar.sh
          services:
            - docker
definitions:
  services:
    docker:
      memory: 3072
